version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  app:
    build: .
    image: ashkarin/slvm
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      DEBUG: 'true'
      APP_PORT: '8080'
      DB_HOST: 'postgres'
      DB_USER: 'postgres'
      DB_PASS: 'postgres'
      DB_PORT: '5432'