columns:
    OBJECTID_1: [object_id_1, int]
    OBJECTID: [object_id, int]
    gml_parent: [gml_parent, str]
    gml_pare_1: [gml_pare_1, str]
    gml_id: [gml_id, int]
    ADRESSID: [address_id, int]
    ADRESSID_x: [address_id_x, int]
    HNR: [hnr, int]
    HNR_xsi_ni: [hnr_xsi_ni, int]
    HNR_ZUSATZ: [hnr_zusatz, str]
    HNR_ZUSA_1: [hnr_zusatz_1, int]
    STR_NR: [str_nr, int]
    STR_NR_xsi: [str_nr_xsi, int]
    STR_NAME: [str_name, str]
    STR_NAME_x: [str_name_x, int]
    PLZ: [plz, int]
    PLZ_xsi_ni: [plz_xsi_ni, int] 
    BEZ_NAME: [bez_name, str]
    BEZ_NAME_x: [bez_name_x, int]
    BEZ_NR: [bez_nr, int]
    BEZ_NR_xsi: [bez_nr_xsi, int]
    ORT_NAME: [ort_name, str]
    ORT_NAME_x: [ort_name_x, int]
    ORT_NR: [ort_nr, int]
    ORT_NR_xsi: [ort_nr_xsi, int]
    PLR_NAME: [plr_name, str]
    PLR_NAME_x: [plr_name_x, int]
    PLR_NR: [plr_nr, int]
    PLR_NR_xsi: [plr_nr_xsi, int]
    BLK: [blk, int]
    BLK_xsi_ni: [blk_xsi_ni, int]
    ADR_DATUM: [adr_datum, datetime]
    ADR_DATUM_: [adr_datum_, int]
    STR_DATUM: [str_datum, datetime]
    STR_DATUM_: [str_datum_, int]
    QUALITAET: [qualitaet, str]
    QUALITAET_: [qualitaet_, int]
    TYP: [typ, str]
    TYP_xsi_ni: [typ_xsi_ni, int]
    GML_ID_xsi: [gml_id_xsi, int]